[package]
name = "libsolenoid"
version = "0.1.0"
authors = ["Ricky Han <rickylqhan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = { version = "2.0", package = "rustc-hex" }
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm8-0"] }

structopt = { version = "0.3", default-features = false }

serde_json = "1.0.59"
serde = { version = "1.0", features = ["derive"] }

log = "0.4.0"
env_logger = "0.7.1"

tiny-keccak = "1.4"
ethereum-types = "0.9.0"
uint = "0.8.2"

bindgen = "0.55.1"
primitive-types = "0.7.2"

[[bin]]
name = "solenoid"
path = "src/bin.rs"
